### ISSUE TITLE
Carthage doesn't produce a framework

### ISSUE THREAD

**Issue by rzulkoski** [IBM-Swift/swift-html-entities#31]
After adding `github "IBM-Swift/swift-html-entities" == 3.0.5` to a fresh project and running `carthage update --platform iOS` it finishes successfully but there is no output in the Carthage/Builds/iOS directory.

Any ideas?

**Comment by youming-lin** [comment]
Thanks for the issue. I'm new to Carthage, and I didn't realize that Carthage does the building as well.

The cause of this issue is because this repo is missing `xcodeproj`; `xcodeproj` is not included because this package was originally intended to be consumed via Swift Package Manager (which builds via `swift build` instead of `xcodebuild`).

Currently the two solutions I have is either 1) include `xcodeproj`, which is not optimal because of the Swift 3 -> Swift 4 migration causing `xcodeproj` changes, or 2) include prebuilt binaries, which might increase the download size for Swift Package Manager users.

I'll continue to investigate a solution.

**Comment by rzulkoski** [comment]
Cool, thanks for the quick reply. I would agree that the xcodeproj doesn't sound like the way to go.

I'm also not super familiar with how to integrate Carthage from a Framework owner standpoint, but I'm not sure that the prebuilt binaries would necessarily live directly in your repo. You may want to take a look at the following:

- [Carthage - Archive Prebuilt Frameworks into one zip file](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file)
- [Carthage - Use travis-ci to upload your tagged pre-built frameworks](https://github.com/Carthage/Carthage#use-travis-ci-to-upload-your-tagged-prebuild-frameworks)
- [Branch.io - Releases](https://github.com/BranchMetrics/ios-branch-deep-linking/releases) (Notice how the Branch.framework.zip lives as a download and not in the actual repo, but Carthage picks it up)

**Comment by youming-lin** [comment]
Thanks for the links. I took a look at the Travis setup, and it seems complicated given I'm doing matrix builds. I'm not clear on how the Travis deploy process works with matrix builds on different environments. 

For now, I'll go with uploading an `xcodeproj`.

**Comment by youming-lin** [comment]
I've tagged a [new release](https://github.com/IBM-Swift/swift-html-entities/releases/tag/3.0.6) that fixes this issue. Thanks again for pointing out this issue.

**Comment by rzulkoski** [comment]
Awesome, thanks for the quick fix!

In other news, it looks like the minimum deployment target is 10.3 for iOS. Any chance you could lower it to 9.1 or lower? Eventually we will deprecate support for iOS 9, but not quite yet.

**Comment by youming-lin** [comment]
Looks like the generated `xcodeproj` didn't set an iOS SDK target level, so I'm assuming it defaults to the latest.

I'll open a new issue for this and continue investigation.

**Comment by youming-lin** [comment]
Version 3.0.7 should work on iOS 9 now.
